import { describe, expect, it } from "vitest";

import {
  MIN_PUBLISHED_SEED_COUNT,
  SEED_INTERVIEW_VIDEOS,
} from "@/lib/videos/seed-data";

describe("interview video seed data", () => {
  it("has stable ids and unique ids", () => {
    const ids = SEED_INTERVIEW_VIDEOS.map((v) => v.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const video of SEED_INTERVIEW_VIDEOS) {
      expect(video.id.length).toBeGreaterThan(0);
      expect(video.title.length).toBeGreaterThan(0);
    }
  });

  it("meets minimum published count", () => {
    const published = SEED_INTERVIEW_VIDEOS.filter((v) => v.published);
    expect(published.length).toBeGreaterThanOrEqual(MIN_PUBLISHED_SEED_COUNT);
  });

  it("gives every row a public http(s) url and at least one category tag", () => {
    for (const video of SEED_INTERVIEW_VIDEOS) {
      expect(video.url.startsWith("https://") || video.url.startsWith("http://")).toBe(
        true
      );
      expect(video.categoryTags.length).toBeGreaterThanOrEqual(1);
    }
  });

  it("includes at least one unpublished row for filter checks", () => {
    expect(SEED_INTERVIEW_VIDEOS.some((v) => !v.published)).toBe(true);
  });

  it("does not claim AI-generated video content in titles or summaries", () => {
    for (const video of SEED_INTERVIEW_VIDEOS) {
      const hay = `${video.title} ${video.summary}`.toLowerCase();
      expect(hay).not.toMatch(/ai[- ]generated video/);
      expect(hay).not.toMatch(/generated by ai/);
    }
  });
});
